### ISSUE TITLE
url rewriting is breaking reload

### ISSUE THREAD

**Issue by backpacker69** [PeerAssets/chizukeki#13] opened 2018-05-07 16:13 UTC
appending wallet and assets to location makes refresh impossible

**Comment by micimize** [comment] 2018-05-17 15:14
I think this is happening because the gh-pages rewrite rules I specified were specific to my domain. Will investigate further

**Comment by micimize** [comment] 2018-05-21 23:43
fixed by fa254461fd7664b51541ce01ab1a4b75ff149bd9 - committed the [spa-github-pages](https://github.com/rafrex/spa-github-pages#usage-instructions) 404.html to prevent further regression (was being excluded because it's in a `dist` subdirectory)

**Closed by micimize** 2018-05-21 23:43 UTC
Labels: bug, regression
