### ISSUE TITLE
transactions from the future

### ISSUE THREAD

**Issue by bananenwilly** [PeerAssets/chizukeki#50] opened 2018-07-23 11:39 UTC
![image](https://user-images.githubusercontent.com/11148913/43074499-c56e409a-8e7d-11e8-910e-1b8cf5d3a4fb.png)

this might have something to do with a faulty system clock... I'm having the same issue on github. very weird.

![image](https://user-images.githubusercontent.com/11148913/43074579-17f9b038-8e7e-11e8-8f02-e94b1f8946ec.png)

**Comment by micimize** [comment] 2018-07-23 14:09
if you're having the same issue on github, it probably is your system clock or a browser setting

**Comment by micimize** [comment] 2018-07-28 14:19
closing as I can't reproduce and it really seems like a system clock issue

**Closed by micimize** 2018-07-28 14:19 UTC
